GET http://localhost:9090/products

###
GET http://localhost:9090/products?category=2
###
POST  http://localhost:9090/products
Content-Type: application/json

{
    "model": "iPhjh",
    "description": "string",
    "price": 123,
    "catId":1
}

###
DELETE http://localhost:9090/products/4



